### ISSUE TITLE
No new mail notification

### ISSUE THREAD

**Issue by calicofeline** [thunderbird/thunderbird-android#3205]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Sound and light blink notification when new mail arrives. Been using k9 for years, on many different phones, with no issues. This issue started about a week ago.

### Actual behavior
Mail arrives, not notification at all, no sound, no light blink,  no vibration, no email icon. Only know there is new mail by going into app and looking at each account to see new mail.

### Steps to reproduce
1. After reading on existing issue I thought it was related to the Quiet Time setting. Turned Quiet Time off, still no mail notification.
2.Rebooted phone, no mail notification
3.Notifications were working up until about a week ago.  All other phone notifications are working, i.e. text sounds, phone ring sound, new news alerts, etc.

### Environment
K-9 Mail version: 5.403

Android version: 8.1.0 Security patch Feb. 5, 2018

Account type (IMAP, POP3, WebDAV/Exchange):  14 separate IMAP accounts, none of the accounts are receiving notifications. Phone type = Pixel 2. New mail notifications were working on this phone up to about a week ago.

**Comment by cketti** [comment]
Did you maybe disable notifications for K-9 Mail in Android settings?

**Comment by calicofeline** [comment]
Hi cketti, that was a good thought. Just double checked Android setting for K-9 Mail....notifications are all set to on, yet not receiving email notifications.

**Comment by atomGit** [comment]
same here on clark (moto x pure), dirty unicorns 7.x, clean install

note also that clark does not have a colored LED - maybe that is a common thread here?

[url=https://github.com/k9mail/k-9/issues/2369]#2369[/url]
[url=https://github.com/k9mail/k-9/issues/3160]#3160[/url]
[url=https://github.com/k9mail/k-9/issues/3098]#3098[/url]

**Comment by gazzawazza** [comment]
hi all

posted about this issue on another thread, which I've noticed is closed. Not sure whether to re-post my content and info, as this is open?

[https://github.com/k9mail/k-9/issues/2999#issuecomment-378299646](url)

summary is that LED and new mail sound don't work on s8 running official carrier oreo build when new mail is received. Status bar icons do appear though. K9 is v5.403

If both the accounts i use/check have their notification tones re-picked, tone and LEDwork, as least for a bit. App seems to have reverted back to vibration only, even though I've changed nothing and volumes are correct/active/high enough. Very odd.

**Comment by insoptivos** [comment]
I’ve used K-9 for years with my three previous phones, Kitkat-Nougat, and loved every reliable minute.
Now I have a Nokia 6.1 (US) with Oreo 8.1.0 and K-9 v5.403 and notifications just don’t work!  Emails have always been set to search every 1 minute because my main phone use is for emailed jobs being sent to me so this is literally a disaster.  Every so often a notification will appear but that is no help.  Originally I disabled the Gmail app (not a google fan) but today after receiving a 2 hour late email I turned the gmail back on and that seems to be working but I want K-9 back.  

There has to be something in settings, somewhere, to make this work with Oreo.  When I open K-9, sometimes older emails are there, sometimes they’ll start loading and other times I need to refresh to receive them.

**Comment by cgohier** [comment]
Not sure if same issue, but often when I get a notification from K9, the notification is immediately dismissed, within 1 second, without any interaction from my part. I've had this problem for many months.

K9 version 5.600
Android 7.1.1 stock
Moto X Play

**Comment by eugene-bright** [comment]
Old related issue #834
I had the same issue as @cgohier on my Xiaomi A2 light, but after last security update and reboot the problem has gone.

**Comment by Ynjxsjmh** [comment]
In my case, I won't get any notification unless k-9 mail is running regardless in background or foreground. I hope this could help.

**Comment by covex** [comment]
No notification on Unihertz Atom with Android Oreo 8.1, seems like there is no auto-sync either I have to manually refresh folders. I copied my K9 profile from Android 7.

**Comment by robertfoobar** [comment]
Same here since a couple of months. I noticed that notifications actually appear but get canceled immediately resulting in no notification in the long run.

HTC U12+
Android 8.0.0
K9 Version 5.600

**Comment by Tarkleigh** [comment]
I roll-back to version 5.403 and the issue is gone for me. At least on my installation, it definetly was caused by the latest release

**Comment by robertfoobar** [comment]
It's not necessarily only the latest (5.600) release that caused the issue. According to https://github.com/k9mail/k-9/releases there have been a couple of releases that could have introduced it since 5.403 namely: 5.500, 5.501, 5.502, 5.503 and 5.600.

**Comment by lkettenb** [comment]
> notifications actually appear but get canceled immediately resulting in no notification in the long run.

I get exactly the same behavior. 
OnePlus 6
Android 9
K9 5.600

**Comment by covex** [comment]
Is there any solution on the way? This really makes the k9 almost unusable, as I have to manully refresh all folders.

**Comment by lkettenb** [comment]
I installed version [5.403](https://github.com/k9mail/k-9/releases/tag/5.403) as well and the issue is gone.

**Comment by Tagirijus** [comment]
Same problem here on my Huawai P8 Lite 2017 with K-9 Mail 5.600, EMUI and Android 8.0.0 (PRA-LX1 8.0.0.402(C432)). Problem occured around 1-2 weeks ago. It is not only annoying but also a big problem, since I once trusted the notifications regarding my business mails.

I would love to try to install 5.403, but I do not how. Hope this issue will be fixed. Thanks for all the help! (=

**Comment by Tarkleigh** [comment]
Could somebody please add the "bug" label to this issue? Maybe this can speed up the process

**Comment by covex** [comment]
I've tried 5.403 but it did not help, I still do not have notification, and I had to reinitializa my profile. I do not recommand this to "unexperienced" users.

**Comment by davidReward** [comment]
same Issue with Galaxy S5 (klte) and Lineageos 15.1
with Version 5.403 it works...

**Comment by jane1969** [comment]
Exactly the same issue with a Galaxy A8, no notification neither badge icon. Only the widget with the number of unread mails works.

**Comment by jane1969** [comment]
> 
> 
> Exactly the same issue with a Galaxy A8, no notification neither badge icon. Only the widget with the number of unread mails works.

For an unknown reason, I managed to make notifications work sometimes. I can't determinate which conditions make that notifications are shown or not, it seems totally random, as I tried the same sequence after restarting phone.

What I noticed as a constant pattern is that synchro does not occur as long as the K9-mail app is not launched at least once. Though it appears in the background app listing after restarting the phone, there is no synchro until the app comes in the foreground once. Sometimes, it is even necessary to open a folder and close it. The synchro messsage time relates to last sync rather to next sync until this is done. As soon as this indication switches to ongoing duration rather than spent time, the synchro occurs at the frequency required in settings.

Hope it will help improving synchro and notif behaviour.

**Comment by gvampgh** [comment]
Hello developers, it's a great app, but unfortunately I have the same issues with neither push messages nor syncing at programm start. I'm on Lineage, Magisk rooted, Android 9, Samsung S4, app is not battery optimized. PLEASE, please correct this bug, other clients don't have these problems (but others, thats why I like K9).

As a developer I tried to contribute but I get annoying compilation errors regarding ":" constants and unknown xml resources in Android Studio.

**Comment by Ketrel** [comment]
I'm using LineageOS 16 (Pie) on a OnePlus 3T.
I also have the issue where notifications seem to dismiss themselves.

K9 is version 5.600

**Comment by fnadde42** [comment]
Version 5.600 running on Fairphone Open (Android 7.1) via F-Droid.

My notifications appears for like 250 milliseconds before disappearing (much like @cgohier [describes it](https://github.com/k9mail/k-9/issues/3205#issuecomment-437447365)) and when I go into K-9 and into my inbox, the header says "Syncing Disabled" even though I have not disabled it. I went into *Account Settings* and *Fetching mail* and moved the *Folder poll frequency* around a bit and suddenly it starts to sync again saying that its 5 minutes to the next sync. However, give it a while and it's back to "Syncing disabled".

**Comment by JDJADU** [comment]
I just bought a new phone with Android 9 and I have/had the same problem. No sound, no led, only vibrations and notifications on the lock screen. After trying lots of things I have finally found a solution that is working (for me). I gave K9 the right to disturb during DND (do not disturb). DND does not have to be on or set, only the right must be given.

**Comment by ivanpu** [comment]
Same issue here - no notifications with 5.600, notifications work with 5.403 (the previous version on F-Droid).

Android version: 8.0.0
Account type: IMAP

**Comment by zanzara** [comment]
Same issue here:  no notifications with 5.600
When there will be a remedy? So long ongoing this feature.  

The issue seemd to be,  that mail sync gets somehow off. At least this mess is shown on top of the K9 title.

Really annoying. Everything did run so good in 5.010 under Android 6

Running on LOS 16  (Andorid 9), Accounttype: any

**Comment by markasoftware** [comment]
Happening for me too -- Android 9 custom rom, moto g4.

**Comment by Verifirs** [comment]
I have the same problem. Android 9, Lineage OS 16.0.

**Comment by kevinfiol** [comment]
Same problem, Android 8.0, OmniROM, Moto G5 Plus. Set to "Always Sync", but still no notifications.

**Comment by dbasa** [comment]
I have the same issued as @cgohier on my Oneplus 7 Pro with Pie (9) firmware and 5.600 K9 mail. I get notifications but they disappear on their own. Vibration and sound notifications do work.
I tried enabling the led (although my device does not have one) as well as the vibration pattern and for now notifications seem to stay visible.

**Comment by wrapper** [comment]
+1 on the latest beta 5.700

**Comment by piticli5** [comment]
Hello,

I have the same problem, and i found the problem is the optimize of battery in new versions of android.

In xaomi Mi9 I resolve going to (in spanish): ajustes -> buscar por "batería" -> batería y rendimiento -> seleccionar aplicaciones -> K-9 Mail -> sin restricciones

In blackview I resolve going to (in spanish): ajustes -> buscar por "optimiazción" -> optimiazción de batería -> optimiazción de batería -> poner "todas las aplicaciones" -> K-9 Mail -> no optimizar

**Comment by DatAres37** [comment]
I have this problem when my phone is in flight mode and I deactivate it. A notification is shown for like 2 seconds and it disappears for no reason after that time. Missed some mails because of that. Kinda disappointing.

**Comment by roylaprattep** [comment]
Same bug here, Pixel 2 XL, stock rom.

**Comment by Pixy123** [comment]
> I have this problem when my phone is in flight mode and I deactivate it. A notification is shown for like 2 seconds and it disappears for no reason after that time. Missed some mails because of that. Kinda disappointing.

Same problem on mate 10 pro

**Comment by davidhedlund** [comment]
Version 5.704 didn't help on a LG G7 ThinkQ smartphone with Android 9.

**Comment by davidhedlund** [comment]
> It's not necessarily only the latest (5.600) release that caused the issue. According to https://github.com/k9mail/k-9/releases there have been a couple of releases that could have introduced it since 5.403 namely: 5.500, 5.501, 5.502, 5.503 and 5.600.

Version 5.704 didn't help on a LG G7 ThinkQ smartphone with Android 9.

**Comment by JanSchnacki** [comment]
> Hello,
> 
> I have the same problem, and i found the problem is the optimize of battery in new versions of android.

That's it! I have no idea how other words with activated battery optimization are able to show notifications, but this is the actual problem, here.

**Comment by Ketrel** [comment]
Maybe to your specific case, but the first thing I've done since I've started experiencing this was disable battery optimizations for K9, and it's been off ever sense, yet this still occurs.

**Comment by JanSchnacki** [comment]
Darn, ok, still this possible cause was underrepresented in the discussion on this bug. So we apparently have multiple causes.

**Comment by severus-tux** [comment]
Same problem. The latest beta (from f-droid (unstable updates checked)) disables push notification. It only uses fetch. The option "push" in account settings is nowhere to be found. When I switch back to the stable (2 years old) version, the push settings re-appears. Mails are notified instantly. Please fix this. 

(let me know if you need screenshots/logs)

**Comment by KIMWW** [comment]
Same for me since long time. I've downgraded from version 5.600 to 5.403 but it still the same.

**Comment by topas-rec** [comment]
I use a Oneplus 5t on an official Android 10 and had this issue for weeks now.  I resolved it (since two days, E-Mail coming in and notifications are made, the app is not open in background) by disabling battery optimization for this app.

I'll come back here to correct my answer if the issue reappears.

**Comment by woheller69** [comment]
For me this works:
Version 5.403
Battery optimization  off
Unlimited data access

**Comment by schmitzkr** [comment]
I have this same problem.  I have two accounts configured in the same way and from all settings I should get pushed new mail notifications.  Notifications only appear if I open my inbox in either account and refresh the inbox folder.
I'm on Android 11
K9 mail 5.726

**Comment by marc0w** [comment]
Same here, Android 10

**Comment by schmitzkr** [comment]
This was fixed for me in the latest version.  I uninstalled all versions of K9mail and reinstalled latest beta from fdroid and notifications work now.  On Android 11.

**Comment by quyleanh** [comment]
Same here. Need to open app and refresh to get notification.
Version 5.731
Battery optimization off
Unlimited data access

**Comment by cketti** [comment]
A lot of these problems seem to be caused by K-9 Mail 5.600 not syncing reliably in the background on modern Android versions. K-9 Mail 5.8xx has fixed this issue. If you're still having trouble with notifications please use the [forum](https://forum.k9mail.app/) first (and please use the search before you post). If it turns out to be a bug we'll ask you to create a new issue.
